---
name: ci
'on': [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Checkout copilot-sdk v1.0.8
        uses: actions/checkout@v7
        with:
          repository: 'github/copilot-sdk'
          ref: 'v1.0.8'
          path: 'copilot-sdk'
          fetch-depth: 0

      # - name: prepare copilot-sdk
      #   run: echo "PYTHONPATH=${{ github.workspace }}/copilot-sdk/python:${PYTHONPATH}" >> $GITHUB_ENV

      - name: Extract copilot-sdk dependencies -> requirements-cop.txt
        env:
          TARGET_FILE: ${{ github.workspace }}/copilot-sdk/python/pyproject.toml # set to your file
        shell: bash
        run: |
          # Extract copilot-sdk dependencies -> requirements-cop.txt
          grep -A 5 "dependencies\s*=" "$TARGET_FILE" | \
            grep -o '"[^"]*"' | \
            tr -d '"' > requirements-cop.txt
          cat requirements-cop.txt

      # - name: Extract copilot-sdk test(dev) dependencies -> requirements-cop-dev.txt
      #   env:
      #     TARGET_FILE: ${{ github.workspace }}/copilot-sdk/python/pyproject.toml # set to your file
      #   shell: bash
      #   run: |
      #     # Extract copilot-sdk test(dev) dependencies -> requirements-cop-dev.txt
      #     grep -A 9 "dev\s*=" "$TARGET_FILE" | \
      #       grep -o '"[^"]*"' | \
      #       tr -d '"' > requirements-cop-dev.txt
      #     cat requirements-cop-dev.txt


      - uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - name: Install deps copilot-sdk deps and deps for pytest.
        run: python -m pip install --upgrade pip && python -m pip install -r requirements-cop.txt -r requirements-dev.txt # -r requirements-cop-dev.txt

      - name: Prepare tests
        run: |
          FILEA="server.py"
          FILEB="patch-for-test-server.py"

          # Step 1: mark matching lines with temporary comment
          sed -i 's/^from copilot.*/# REPLACED_CONTENT/' "$FILEA"
          # Step 2: keep only the first instance of the comment, delete duplicates
          awk '$0 == "# REPLACED_CONTENT" { if (!found) { found=1; print } next } { print }' "$FILEA" > "$FILEA.tmp" && mv "$FILEA.tmp" "$FILEA"
          # Step 3: replace the single remaining comment with contents of fileB
          awk -v f="$FILEB" '/# REPLACED_CONTENT/ { system("cat " f); next } { print }' "$FILEA" >tmp && mv tmp "$FILEA"

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/copilot-sdk/python:${PYTHONPATH}
        run: python -m pytest -q --ignore=copilot-sdk
